#lang racket

; go to https://p5js.org/reference/ and run
; Array.from(document.getElementsByClassName(code)).map(function(v) {return v.hash.substring(5)})
; find/replace "/,/etc to make it into a list of symbols
; add 'var at the top
; then delete:
; - everything from 'let to 'while
; - 'draw, 'setup
; (cf. John 8:7)

(provide p5-defs)

;(define p5-defs '(var this createVector createCanvas fill mouseIsPressed mouseX mouseY ellipse day text))

(define p5-defs '(import
                  describe
                  describeElement
                  textOutput
                  gridOutput
                  print
                  frameCount
                  deltaTime
                  focused
                  cursor
                  frameRate
                  noCursor
                  displayWidth
                  displayHeight
                  windowWidth
                  windowHeight
                  windowResized
                  width
                  height
                  fullscreen
                  pixelDensity
                  displayDensity
                  getURL
                  getURLPath
                  getURLParams
                  alpha
                  blue
                  brightness
                  color
                  green
                  hue
                  lerpColor
                  lightness
                  red
                  saturation
                  Color
                  background
                  clear
                  colorMode
                  fill
                  noFill
                  noStroke
                  stroke
                  erase
                  noErase
                  arc
                  ellipse
                  circle
                  line
                  point
                  quad
                  rect
                  square
                  triangle
                  ellipseMode
                  noSmooth
                  rectMode
                  smooth
                  strokeCap
                  strokeJoin
                  strokeWeight
                  bezier
                  bezierDetail
                  bezierPoint
                  bezierTangent
                  curve
                  curveDetail
                  curveTightness
                  curvePoint
                  curveTangent
                  beginContour
                  beginShape
                  bezierVertex
                  curveVertex
                  endContour
                  endShape
                  quadraticVertex
                  vertex
                  normal
                  plane
                  box
                  sphere
                  cylinder
                  cone
                  ellipsoid
                  torus
                  Geometry
                  loadModel
                  model
                  HALF_PI
                  PI
                  QUARTER_PI
                  TAU
                  TWO_PI
                  DEGREES
                  RADIANS
                  preload
                  remove
                  disableFriendlyErrors
                  noLoop
                  loop
                  isLooping
                  push
                  pop
                  redraw
                  p5
                  Element
                  select
                  selectAll
                  removeElements
                  changed
                  input
                  createDiv
                  createP
                  createSpan
                  createImg
                  createA
                  createSlider
                  createButton
                  createCheckbox
                  createSelect
                  createRadio
                  createColorPicker
                  createInput
                  createFileInput
                  createVideo
                  createAudio
                  VIDEO
                  AUDIO
                  createCapture
                  createElement
                  MediaElement
                  File
                  Graphics
                  createCanvas
                  resizeCanvas
                  noCanvas
                  createGraphics
                  blendMode
                  drawingContext
                  setAttributes
                  applyMatrix
                  resetMatrix
                  rotate
                  rotateX
                  rotateY
                  rotateZ
                  scale
                  shearX
                  shearY
                  translate
                  storeItem
                  getItem
                  clearStorage
                  removeItem
                  createStringDict
                  createNumberDict
                  TypedDict
                  NumberDict
                  append
                  arrayCopy
                  concat
                  reverse
                  shorten
                  shuffle
                  sort
                  splice
                  subset
                  float
                  int
                  str
                  boolean
                  byte
                  char
                  unchar
                  hex
                  unhex
                  join
                  match
                  matchAll
                  nf
                  nfc
                  nfp
                  nfs
                  split
                  splitTokens
                  trim
                  deviceOrientation
                  accelerationX
                  accelerationY
                  accelerationZ
                  pAccelerationX
                  pAccelerationY
                  pAccelerationZ
                  rotationX
                  rotationY
                  rotationZ
                  pRotationX
                  pRotationY
                  pRotationZ
                  turnAxis
                  setMoveThreshold
                  setShakeThreshold
                  deviceMoved
                  deviceTurned
                  deviceShaken
                  keyIsPressed
                  key
                  keyCode
                  keyPressed
                  keyReleased
                  keyTyped
                  keyIsDown
                  movedX
                  movedY
                  mouseX
                  mouseY
                  pmouseX
                  pmouseY
                  winMouseX
                  winMouseY
                  pwinMouseX
                  pwinMouseY
                  mouseButton
                  mouseIsPressed
                  mouseMoved
                  mouseDragged
                  mousePressed
                  mouseReleased
                  mouseClicked
                  doubleClicked
                  mouseWheel
                  requestPointerLock
                  exitPointerLock
                  touches
                  touchStarted
                  touchMoved
                  touchEnded
                  createImage
                  saveCanvas
                  saveFrames
                  Image
                  loadImage
                  image
                  tint
                  noTint
                  imageMode
                  pixels
                  blend
                  copy
                  filter
                  get
                  loadPixels
                  set
                  updatePixels
                  loadJSON
                  loadStrings
                  loadTable
                  loadXML
                  loadBytes
                  httpGet
                  httpPost
                  httpDo
                  XML
                  createWriter
                  PrintWriter
                  save
                  saveJSON
                  saveStrings
                  saveTable
                  Table
                  TableRow
                  day
                  hour
                  minute
                  millis
                  month
                  second
                  year
                  abs
                  ceil
                  constrain
                  dist
                  exp
                  floor
                  lerp
                  log
                  mag
                  map
                  max
                  min
                  norm
                  pow
                  round
                  sq
                  sqrt
                  fract
                  createVector
                  Vector
                  noise
                  noiseDetail
                  noiseSeed
                  randomSeed
                  random
                  randomGaussian
                  acos
                  asin
                  atan
                  atan2
                  cos
                  sin
                  tan
                  degrees
                  radians
                  angleMode
                  textAlign
                  textLeading
                  textSize
                  textStyle
                  textWidth
                  textAscent
                  textDescent
                  textWrap
                  loadFont
                  text
                  textFont
                  Font
                  orbitControl
                  debugMode
                  noDebugMode
                  ambientLight
                  specularColor
                  directionalLight
                  pointLight
                  lights
                  lightFalloff
                  spotLight
                  noLights
                  loadShader
                  createShader
                  shader
                  resetShader
                  texture
                  textureMode
                  textureWrap
                  normalMaterial
                  ambientMaterial
                  emissiveMaterial
                  specularMaterial
                  shininess
                  Shader
                  camera
                  perspective
                  ortho
                  frustum
                  createCamera
                  Camera
                  setCamera
                  ))